set -e
# Do not edit this file unless you know what you are doing as you cannot use merge.sh to merge changes to merge.sh.
# If you aren't sure and want a change made to this file contact me (MichaelC)
echo "This script will merge all the branches as is required. To use this script you need to have setup both the private and public parts of the phpBB website and this is designed for use by core committers to the phpBB website only."
echo ""
echo "Just set up the site as per https://www.phpbb.com/community/viewtopic.php?f=34&t=2160102 (specifically steps II and IV)"
echo ""
echo "This script should exit should any problems occur but please watch it and should you notice anything go wrong, please hit Ctrl + C to stop script execution"
echo ""
echo "Running this script is not enough to deploy onto .com. Bamboo will handle merging private into www1-stable which is the branch used to update .com and that will only occur if tests pass. If this is an urgent fix and cannot wait for bamboo run the deploy.sh script immediately after this script"
echo ""
echo "Options:"
echo "--skip-tests | Skips running tests"
echo "--path       | Runs ./tests.sh instead of tests.sh"
echo ""
echo "   ------------ This script will now begin ------------   "
echo ""
echo "Git status:"
git status -sb
echo "If that showed anything abort now!!!!!!"
echo "Hit enter to continue (once you've read the message at the top and checked there was nothing uncommitted on the git status"
read x
echo "$ git fetch public"
git fetch public
echo ""
echo "$ git fetch private"
git fetch private
echo ""
echo "$ git checkout master"
git checkout master
echo ""
echo "$ git merge public/master && git merge private/master"
git merge public/master --no-edit --ff-only
git merge private/master --no-edit --ff-only
echo ""
echo "Install composer deps:"
echo "------------------------"
php composer.phar install --ignore-platform-reqs
if [ "$1" != "--skip-tests" ]
then
	echo ""
	echo "Tests:"
	echo "--------"
	if [ "$1" == "--path" ]
	then
		./tests.sh
	else
		tests.sh
	fi
fi
echo ""
echo "Checkout private branch:"
echo "--------------------------"
git checkout private
echo ""
echo "$ git merge private/private"
git merge private/private
echo ""
echo "Merge master branch into private branch:"
echo "-------------------------------------------"
git merge master --no-edit
echo ""
echo "Checkout master branch:"
echo "--------------------------"
git checkout master
echo ""
echo "Push master branch to public repository:"
echo "------------------------------------------------------"
git push public master
echo ""
echo "Push master & private branches to private repository:"
echo "--------------------------------------------------------------------------"
git push private master private
echo "DONE!!"
